### ISSUE TITLE
Unknown Exception

### ISSUE THREAD

**Issue by CrispyBaconUk** [Nader-Sl/Hackemon#18]
Unsure what happened everything was fine, then it stopped catching pokemon / stopped sniping (could still manually snipe) not collecting items from pokestops.

I quit the program and went back to terminal and found the following - unsure if this was the cause of the issue or not.

I now cant open the program at all and get the following

`Exception in thread "Thread-5" java.lang.NullPointerException
	at salt.hk.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

MacOS

Stacktrace below
`I/Main: Use incense result: SUCCESS
salt.jt: Unknown exception occurred. 
	at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
	at salt.iH.foaJ3vbbSL(Unknown Source)
	at com.hackemon.new.K0M0qVvnMS(Unknown Source)
	at com.hackemon.new.K0M0qVvnMS(Unknown Source)
	at com.hackemon.Hackemon.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at salt.jA.get(Unknown Source)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 6 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at salt.jC.VCE6C6VOao(Unknown Source)
	at salt.jz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
I/Main: Use incense result: SUCCESS
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 492 >= 1
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.DefaultListModel.getElementAt(DefaultListModel.java:89)
	at org.pushingpixels.substance.internal.ui.SubstanceListUI.paintCell(SubstanceListUI.java:568)
	at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:317)
	at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:240)
	at org.pushingpixels.substance.internal.ui.SubstanceListUI.__org__pushingpixels__substance__internal__ui__SubstanceListUI__update(SubstanceListUI.java:788)
	at org.pushingpixels.substance.internal.ui.SubstanceListUI.update(SubstanceListUI.java)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
I/Main: Use incense result: SUCCESS
salt.jt: Unknown exception occurred. 
	at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
	at salt.iH.foaJ3vbbSL(Unknown Source)
	at com.hackemon.new.K0M0qVvnMS(Unknown Source)
	at com.hackemon.Hackemon.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: salt.jw: Recieved bad response code:
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	... 4 more
Caused by: java.util.concurrent.ExecutionException: salt.jw: Recieved bad response code:
	at salt.jA.get(Unknown Source)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 5 more
Caused by: salt.jw: Recieved bad response code:
	at salt.jz.K0M0qVvnMS(Unknown Source)
	at salt.jz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.lang.ArrayIndexOutOfBoundsException: 5
	at com.hackemon.do.K0M0qVvnMS(Unknown Source)
	at salt.jz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
GoogleMapView.mapResized: triggering resize event
GoogleMapView.mapResized: triggering resize event
java.net.SocketException: Operation timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:675)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at com.pokegoapi.util.do.WwJfxMLBTm(Unknown Source)
	at com.hackemon.util.web.PokeSnipeUtil.n8iB9BIuRZ(Unknown Source)
	at com.hackemon.byte.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
java.net.SocketException: Operation timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:675)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at com.pokegoapi.util.do.WwJfxMLBTm(Unknown Source)
	at com.hackemon.util.web.PokeSnipeUtil.n8iB9BIuRZ(Unknown Source)
	at com.hackemon.byte.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by dogshampooo** [comment]
same here, someone said to use a vpn but im not finding any that works

**Comment by CrispyBaconUk** [comment]
Works fine on windows
