### ISSUE TITLE
Incense causing crash?

### ISSUE THREAD

**Issue by Joannou1** [Nader-Sl/Hackemon#33]
I'm not sure what the ultimate source / cause of this is, but it's happened twice within an hour of starting the bot each time.

`Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at salt.lT.QeSuAnCe00(Unknown Source)
        at salt.lQ.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
I/Main: Use incense result: SUCCESS
salt.lK: Unknown exception occurred.
        at com.pokegoapi.util.do.K0M0qVvnMS(Unknown Source)
        at salt.lQ.K0M0qVvnMS(Unknown Source)
        at salt.kH.e6pMKPrx28(Unknown Source)
        at salt.kH.Mjslg5T2j9(Unknown Source)
        at salt.lw.K0M0qVvnMS(Unknown Source)
        at salt.iY.XSwGyuNMN1(Unknown Source)
        at salt.iY$$Lambda$245/1803308523.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        ... 8 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at salt.lR.VCE6C6VOao(Unknown Source)
        at salt.lR.get(Unknown Source)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 9 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at salt.lT.QeSuAnCe00(Unknown Source)
        at salt.lQ.run(Unknown Source)
        ... 1 more
Press any key to continue . . .`

I must say though, the bot is working great regardless, got to level 14 from 1 within 3 hours with some fairly slow settings and a short range.
Just wondering, does this program spoof altitude and all that? Cause I live in the mountains at above 7000 ft.. I heard that a lot of these send 0ft, which would not be good.

Oh also, an ability to blacklist / exclude some stops would be good, sometimes it walks far away from the hotspot I'd like it to be at and gets stuck there.

**Comment by wintermute0001** [comment]
@Nader-Sl  can you confirm that altitude is being set?  Otherwise it might be an obvious ban flag.
